title          : Pejzero
author         : Whyjay Zheng
copyright      : "2021-2022"  
logo           : logo.png

html:
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://whyjz.github.io/pejzero

# bibtex_bibfiles:
#  - refs.bib

# bibtex_reference_style: author_year

repository:
  url: https://github.com/whyjz/pejzero
  branch: main
  path_to_book: jupyter-book

launch_buttons:
  notebook_interface: "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  # thebe: true
  
execute:
  execute_notebooks : 'off'
  timeout           : 30
  allow_errors      : false